contentColumnType: text
fieldGroup: dbffa377-8ee3-4cd7-b760-40af17b622cd
handle: testimonialTitle
instructions: ''
name: 'Testimonial Title'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
