contentColumnType: text
fieldGroup: ba01e3fc-db01-4180-a444-42724273c5be
handle: testimonialName
instructions: ''
name: 'Testimonial Name'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
