enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  46ee6e16-4e9c-43a2-a16e-317808f888d8:
    enabledByDefault: true
    hasUrls: true
    template: index
    uriFormat: __home__
type: single
